version: 2.1

default_test_steps: &default_test_steps
  steps:
    - checkout
    - run: yarn
    - run: yarn test

jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    environment:
      PERCY_ENABLE: 0
    <<: *default_test_steps
  percy_test:
    # We've opted this node version to be the one that runs and reports Percy's status
    docker:
      - image: circleci/node:12-browsers
    <<: *default_test_steps
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: npx semantic-release

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test
      - percy_test
      - release:
          requires:
            - test
            - percy_test
