describe('@percy/cypress', function() {
  const TEST_URL = `http://localhost:8000`

  beforeEach(function() {
    // Make sure we start each test with a clean slate.
    cy.clearLocalStorage()
    // Load the app and verify that it is in fact being loaded correctly.
    cy.visit(TEST_URL)
    cy.get('.todoapp').should('exist')
  })

  it('Snapshots with autogenerated name', function() {
    cy.percySnapshot()
  })

  it('Snapshots with provided name', function() {
    cy.percySnapshot('Explicitly given name')
  })

  it('Snapshots with provided name and widths', function() {
    cy.percySnapshot('Snapshot with widths', { widths: [768, 992, 1200] })
  })

  it('Snapshots with provided name and minHeight', function() {
    cy.get('.todoapp').should('exist')
    cy.percySnapshot('Snapshot with minHeight', { minHeight: 2000 })
  })

  it('Correctly takes multiple snapshots in one test', function() {
    // Enter a new todo.
    cy.get('.new-todo').type('A thing to accomplish {enter}')
    cy.get('.todo-count').should('contain', '1 item left')
    cy.percySnapshot('Multiple snapshots #1 -- 1 todo left')

    // Click it off -- it should be marked as completed.
    cy.get('.toggle').click()
    cy.get('.todo-count').should('contain', '0 items left')
    cy.percySnapshot('Multiple snapshots #2 -- 1 checked-off todo')
  })
})
