describe('@percy/cypress', function() {

  describe('with local app', function() {

    beforeEach(function() {
      // Make sure we start each test with a clean slate.
      cy.clearLocalStorage()
      // Load the app and verify that it is in fact being loaded correctly.
      cy.visit('http://localhost:8000')
      cy.get('.todoapp').should('exist')
    })

    it('snapshots with autogenerated name', function() {
      cy.percySnapshot()
    })

    it('snapshots with provided name', function() {
      cy.percySnapshot('Explicitly given name')
    })

    it('snapshots with provided name and widths', function() {
      cy.percySnapshot('Snapshot with widths', { widths: [768, 992, 1200] })
    })

    it('snapshots with provided name and minHeight', function() {
      cy.get('.todoapp').should('exist')
      cy.percySnapshot('Snapshot with minHeight', { minHeight: 2000 })
    })

    it('correctly takes multiple snapshots in one test', function() {
      // Enter a new todo.
      cy.get('.new-todo').type('A thing to accomplish {enter}')
      cy.get('.todo-count').should('contain', '1 item left')
      cy.percySnapshot('Multiple snapshots #1 -- 1 todo left')

      // Click it off -- it should be marked as completed.
      cy.get('.toggle').click()
      cy.get('.todo-count').should('contain', '0 items left')
      cy.percySnapshot('Multiple snapshots #2 -- 1 checked-off todo')
    })
  })

  describe('with live sites', function() {

    it('snapshots HTTPS website', function() {
      cy.visit('https://polaris.shopify.com/')
      cy.percySnapshot('Polaris HTTPS', { widths: [768, 992, 1200] })
    })

    it('snapshots website with strict CSP', function() {
      cy.visit('https://buildkite.com/')
      cy.percySnapshot('Buildkite HTTPS + CSP', { widths: [768, 992, 1200] })
    })
  })

})
