name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Percy Test
        uses: percy/exec-action@master
        with:
          command: "node run-tests.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
