name: Test
on: 
  push:
  workflow_dispatch:
    inputs:
      branch:
        required: false
        type: string
        default: master
permissions:
  contents: read
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions-ecosystem/action-regex-match@9e6c4fb3d5e898f505be7a1fb6e7b0a278f6665b # v2.0.2
        id: regex-match
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          text: ${{ github.event.inputs.branch }}
          regex: '^[a-zA-Z0-9_/\-]+$'
      - name: Break on invalid branch name
        run: exit 1
        if: ${{ github.event_name == 'workflow_dispatch' && steps.regex-match.outputs && steps.regex-match.outputs.match == '' }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn
      - name: Set up @percy/cli from git
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          CLI_BRANCH: ${{ github.event.inputs.branch }}
        run: |
          cd /tmp
          git clone --branch "$CLI_BRANCH" --depth 1 https://github.com/percy/cli
          cd cli
          PERCY_PACKAGES=`find packages -mindepth 1 -maxdepth 1 -type d | sed -e 's/packages/@percy/g' | tr '\n' ' '`
          git log -1
          yarn
          yarn build
          yarn global:link
          cd "$GITHUB_WORKSPACE"
          yarn remove @percy/cli && yarn link `echo $PERCY_PACKAGES`
          npx percy --version
      - run: yarn test:coverage
